Virtual assistant chat bot
Knox-AAU/React-UI pull request #23
Opened 2021-11-24 07:52 UTC by Zzeeker

Adds a functional Chat Bot that connects to the Virtual Assistant API and displays unformatted information from Wikidata

2021-11-24 11:07 UTC, JSJCoding commented on Server/server.js
> +      console.log(e)
```diff
- console.log(e)
```

2021-11-24 11:08 UTC, BjoerklundJacob commented on knox-ui/src/Shared_components/VirtualAssistant.js
> +      ) //Formats the response at adds it to the display in the chat area
```suggestion
      ) //Formats the response and adds it to the display in the chat area
```

2021-11-24 11:10 UTC, BjoerklundJacob commented on knox-ui/src/Shared_components/VirtualAssistant.js
> +          }
```suggestion
          if (json === null) {
              self.setState({ loading: false, result: 'Something went wrong...' });
              return;
          }
          self.setState({ loading: false, result: this.formattedResponse(JSON.parse(json), search) });
```

2021-11-24 11:10 UTC, JSJCoding approved these changes
Are we using SQLite?

2021-11-24 11:12 UTC, BjoerklundJacob requested changes
Har suggested nogle changes og den der .vs/...sqlite skal nok i gitignore

2021-11-26 08:22 UTC, JSJCoding approved these changes

2021-11-26 08:26 UTC, BjoerklundJacob approved these changes
Ser fint ud, men hele .vs kunne nok også have været gitignored :)

2021-11-26 08:45 UTC, merged